config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  # resources :companies, except: :show do
  # get :show, on: :collection, as: :show
  # end
    resources :users do
       resources :companies
  end

  root 'jobs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
	belongs_to :category
   
	
	
  has_attached_file :image, styles: {  medium: "800x800>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  # validates_attachment_presence :image
  validates :title, presence: true
  validates :title, length: {minimum: 5, maximum: 15}
  validates :description,length: {minimum: 10, maximum: 400}
  # validates_attachment_presence :image "Image cann't be blank
   validates :jobclosedate,presence: true
  
  # private
  # def future_date
  # errors.add(:jobclosedate, "can't be in the past") if jobclosedate < Date.today
  # end

  
  # validates :price, numericality: {greater_than: 20}
  # validates :intro, length: {in: 50..200}
  # validates :terms_of_service, acceptance: {on: :create} # only validates if new_record?
  # validates :sku, format: {with: /\A[a-zA-Z]+\z/, message: "only allows letters"}
  
end

app/controllers/jobs_controller.rb
	class JobsController < ApplicationController
		before_action :find_job, only: [:show, :edit, :update, :destroy]
		before_action :authenticate_user!,except:[:index, :show], notice: 
		
		def index
			if params[:category].blank?
				@jobs = Job.all.order("created_at DESC")
			else
				@category_id = Category.find_by(name: params[:category]).id
				@jobs = Job.where(category_id: @category_id).order("created_at DESC")
		    end
		end

		def show
		end

		def new
			
			   @job = current_user.jobs.build       
		end

		def create
			@job = current_user.jobs.build(jobs_params)

			if @job.save
				flash[:success]= "success"
				redirect_to @job
			else
				flash[:error]=@job.errors.full_messages
				render "new"
			end
		end

		def edit
		end

		def update
			if @job.update(jobs_params)
				redirect_to @job
	        else
	        	render "Edit"
	        end
		end

		def destroy
			@job.destroy
		redirect_to root_path
		end

		private

		def jobs_params
			params.require(:job).permit(:title, :description, :company, :category_id, :image,:jobclosedate)
		end

		def find_job
			@job = Job.find(params[:id])
		end

		# def require_login
		#     unless current_user
		#       flash[:error] = "You must be logged in to the post a Job"
		#       redirect_to new_user_session_path 
		#      end
		 #end

	end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job,validation:true ,html: { mutlipart: true, class: 'form-horizontal'}) do |f| %>
	<%= f.input :title, label: "Job Title", input_html: { class: "form-control"}%>
	<%= f.input :description, label: "Job Description", input_html: { class: "form-control" }%>
	<%= f.input :company, label: "Your Company", input_html: { class: "form-control" }%>
	<%= f.collection_select :category_id,Category.all, :id, :name, {promt: "Choose a category" }%>

	<div class="dateset" data-behaviour='datepicker' id='datepicker'>
	    <%= f.input_field :jobclosedate,label: "Closing Date",:as => :string, input_html: { class: "datepicker",value: Time.now.strftime('%d-%m-%Y') } %>
    </div>

	<br>
	<br>
	<%= f.file_field :image,  input_html: { class: "form-control", required: true }%>
	
	<br>
	<br>
	<%= f.button :submit, input_html: {class: "button button button1"}%>

	<% end %>
	<div class="input-daterange" data-behaviour='datepicker' id="datepicker">
   <input type="text" class="input-small" name="start" />

<script type="text/javascript">

  $('.datepicker').datepicker()
  $('[data-behaviour~=datepicker]').datepicker();

</script>

app/views/jobs/_formtest.html.haml
= simple_form_for(@job,validation:true ,html: { mutlipart: true, class: 'form-horizontal'}) do |f|
	= f.input :title, label: "Job Title", input_html: { class: "form-control"}
	= f.input :description, label: "Job Description", input_html: { class: "form-control" }
	= f.input :company, label: "Your Company", input_html: { class: "form-control" }
	= f.collection_select :category_id,Category.all, :id, :name, {promt: "Choose a category" }
	= f.input_field :jobclosedate,label: "Closing Date", :as => :string, input_html: { class: "datepicker",value: Time.now.strftime('%d-%m-%Y') }

	%br/
	%br/
	= f.file_field :image,  input_html: { class: "form-control", required: true }
	%br/
	%br/
	= f.button :submit, input_html: {class: "button button button1"}

app/views/jobs/edit.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Job
			.panel-body
				= render 'form'
				= link_to "Back", root_path

app/views/jobs/index.html.erb
<% @jobs.each do |job| %>
                <div class="Border_page" , style='font-weight: bold; margin-bottom: 10px; float: left; padding-bottom: 10px; border-bottom: dotted 1px red;hover {background: #2cdd46;'> 
				<h3><%= link_to job.title, job %></h2>
				<p><%= job.company %></p>
			</div>
				
<% end %>

app/views/jobs/new.html.haml
%h2 New Job
= render 'form'
= link_to "Back", root_path

app/views/jobs/show.html.haml
%h2{:class => "show_job", :id => "message"}= @job.title 
%h4{:class => "show_job_descr"}= simple_format @job.description
%p{style:"font-weight:bold"}= @job.company
%p{style:"font-weight:bold"}= @job.category.name

%br/
%br/

%img= image_tag @job.image.url(:medium)
%br/
%br/
= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }