config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  # resources :companies, except: :show do
  # get :show, on: :collection, as: :show
  # end
    resources :users do
       resources :companies
  end

  root 'jobs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to:user
	has_many:jobs
	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	# before_action :find_company, only: [:show, :edit, :update, :destroy]
        def index
            if params[:user_id] && @user = User.find_by_user_id(id: params[:user_id])
               @companies = @user.companies
           else
               @companies = Company.all
           end
       end
        	
		def show
			 @company = Company.find_by_user_id(current_user.id)
             @company_user_id = current_user.id

			#@company.user_id == current_use
            

		 #@companies = Campany.where(user_id: '1')
		# @company = Company.where(user_id:company.user_id)
			
              # @company_user_id = current_user.id
		end

		def new
			
			   @company = current_user.companies.build     
		end

		def create
			@company = current_user.companies.build(company_params)

			if @company.save
				flash[:success]= "success"
				redirect_to @company
			else
				flash[:error]=@company.errors.full_messages
				render "new"
			end
		end

		def edit
		end

		def update
			if @company.update(company_params)
				redirect_to @company
	        else
	        	render "Edit"
	        end
		end

		def destroy
			@company.destroy
		redirect_to root_path 
		end

		private

		def company_params
			params.require(:company).permit(:c_name, :c_description)
		end

			# def find_company
			# 	@company = Company.find(params[:id]) 
			# end

		# def current_user
  #           @current_user ||= User.find_by(id: session[:user_id])
  #       end

		

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= simple_form_for(@company, html: {class: 'form-horizontal'}) do |f|
	= f.input :c_name, label: "company Name", input_html: { class: "form-control"}
	= f.input :c_description, label: "Company Description", input_html: { class: "form-control" }
	%br/
	%br/
	= f.button :submit

app/views/companies/index.html.erb
<% @companies.each do |company| %>
                <div class="Border_page" , style='font-weight: bold; margin-bottom: 10px; float: left; padding-bottom: 10px; border-bottom: dotted 1px red;hover {background: #2cdd46;'> 
                     <h3><%=company.c_name %></h2>
				     <p><%= company.c_description %></p>

				
			</div>
				
<% end %>

app/views/companies/myprofile.html.haml
= render 'show'
= link_to "Back", root_path

app/views/companies/new.html.haml
%h2 ADD NEW COMPANY
= render 'form'
= link_to "Back", root_path

app/views/companies/show.html.haml
%h2{:class => "show_job", :id => "message"}= @company.c_name
%h4{:class => "show_job_descr"}= simple_format @company.c_description
%br/
%br/
= link_to "Delete", company_path(@company), method: :delete, data: { confirm: "Are you sure?" } 